server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/platform?serverTimezone=Asia/Seoul
    username: ${USER_NAME}
    password: ${USER_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        hbm2ddl:
          auto: none
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
external-server:
  metadata:
    url: https://api.odcloud.kr/api